fix: select the balance with one click
blockstack/explorer pull request #437
Opened 2021-05-04 02:04 UTC by OscarVelandia

## Description

As an interested in the project, I would like to improve the text selection in the address balance. This is needed because it isn't possible to select the balance with click or double click.

This PR was done taking into account the `#418`,  I tested it in windows 10 with notepad, VSCode and Sticky Notes, but I can't reproduce the multi-line paste issue, so, I did an improvement in the select

For details refer to issue #418 by @markmhx

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] API reference/documentation update
- [ x ] Other

## Does this introduce a breaking change?
No

## Are documentation updates required?
No

## Testing information

1. Go to the page http://localhost:3000/address/ST2X2FYCY01Y7YR2TGC2Y6661NFF3SMH0NGXPWTV5?chain=testnet
2. select the STX Balance.

Expected result: it should select all the text.

2021-05-04 02:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/blockstack/explorer?pullRequest=437) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/blockstack/explorer?pullRequest=437) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/blockstack/explorer?pullRequest=437) it.</sub>

2021-05-04 14:56 UTC, aulneau requested changes
Nice, thanks for this! just one comment and then we're good

2021-05-04 14:56 UTC, aulneau commented on src/components/balances/stx-balance-card.tsx
> +              {console.log(totalBalance)}
this should be removed

2021-05-04 16:50 UTC, OscarVelandia commented on src/components/balances/stx-balance-card.tsx
> +              {console.log(totalBalance)}
Done

2021-05-13 16:12 UTC, merged

2021-05-13 16:13 UTC, blockstack-devops commented
:tada: This PR is included in version 1.11.2 :tada:

The release is available on [GitHub release](https://github.com/blockstack/explorer/releases/tag/v1.11.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: